<?php

namespace frontend\controllers;

use deluxcms\member\controllers\FMemberController;

class MemberController extends FMemberController
{
    public function beforeAction($action)
    {
        //设置指定action的title
        $this->setActionTitle($action);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function setActionTitle($action)
    {
        $seoMap = [
            'login' => '会员登录',
            'register' => '会员注册',
            'index' => '会员中心',
            'forget-password' => '忘记密码',
            'update' => '更新个人信息',
            'verify-email' => '邮箱验证',
            'update-email' => '更改邮箱',
            'update-password' => '修改密码',
        ];

        if (isset($seoMap[$action->id])) {
            \frontend\components\Setting::getInstance()->setTitle($seoMap[$action->id]);
        }
    }
}