<?php

namespace frontend\components;

use Yii;
use yii\base\Component;

class Setting extends Component
{
    const SETTING_ID = 'deluxcms_setting';
    const SETTING_SPERATOR = '-';
    private $setting;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->setting = \common\models\Setting::getSetting();
    }

    /**
     * Setting单例
    */
    public static function getInstance()
    {
        if (!Yii::$app->has(self::SETTING_ID)) {
            Yii::$app->set(self::SETTING_ID, ['class' => self::className()]);
        }
        return Yii::$app->get(self::SETTING_ID);
    }

    public function getTitle()
    {
        return $this->setting['title'];
    }

    public function getKeywords()
    {
        return $this->setting['keyword'];
    }
    public function getDescription()
    {
        return $this->setting['description'];
    }

    public function getName()
    {
        return $this->setting['name'];
    }

    public function getCopyright()
    {
        return $this->setting['copyright'];
    }

    public function getFrontMenuId()
    {
        return $this->setting['frontend_menu_id'];
    }

    public function setTitle($value, $append = true, $sperator = '')
    {
        $sperator = empty($sperator) ? self::SETTING_SPERATOR : $sperator;
        $this->setting['title'] = $append ? $this->getTitle() . $sperator . $value : $value;
    }

    public function setDescription($value, $append = false, $sperator = '')
    {
        $sperator = empty($sperator) ? self::SETTING_SPERATOR : $sperator;
        $this->setting['description'] = $append ? $this->getDescription() . $sperator . $value : $value;
    }

    public function setKeywords($value, $append = false, $sperator = '')
    {
        $sperator = empty($sperator) ? self::SETTING_SPERATOR : $sperator;
        $this->setting['keyword'] = $append ? $this->getKeywords() . $sperator . $value : $value;
    }

    /**
     * 设置seo_title, seo_description, seo_keyword
    */
    public function batchSetSeo($model, $tAppend = true, $oAppend = false, $sperator = '')
    {
        if (!empty($model['seo_title'])) $this->setTitle($model['seo_title'], $tAppend, $sperator);
        if (!empty($model['seo_description'])) $this->setDescription($model['seo_description'], $oAppend, $sperator);
        if (!empty($model['seo_keywords'])) $this->setKeywords($model['seo_keywords'], $oAppend, $sperator);
    }
}