<?php

namespace backend\models;

class User extends \common\models\User
{
    const SCENARIO_NEW_USER = 'new_user';
    const SCENARIO_CHANGE_PWD = 'change_user_password';

    public $password;
    public $repassword;

    public function rules()
    {
        return [
            [['username', 'email'], 'required', 'message' => '不能为空'],
            ['username', 'match', 'pattern' => '/^[\w]{1,255}$/', 'message' => '用户名只能为1~255的字母或数字'],
            ['username', 'unique', 'message' => '用户名已经被使用'],
            ['email', 'email', 'message' => '邮箱的格式错误'],
            ['email', 'unique', 'message' => '邮箱已经被使用'],
            ['status', 'in', 'range' => [0, 1], 'message' => '状态不合法'],
            ['password', 'trim', 'on' => [self::SCENARIO_NEW_USER, self::SCENARIO_CHANGE_PWD]],
            ['password', 'string', 'on' => [self::SCENARIO_NEW_USER, self::SCENARIO_CHANGE_PWD], 'min' => 6, 'max' => 255, 'tooShort' => '密码的长度不能小于6位', 'tooLong' => '密码的长度不能大于255'],
            ['repassword', 'compare', 'compareAttribute' => 'password', 'skipOnEmpty' => false, 'message' => '两次密码不一致'],
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->password) {
            $this->setPassword($this->password);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '用户名',
            'email' => '邮箱',
            'status' => '状态',
            'password' => '密码',
            'repassword' => '确认密码',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ];
    }
}